x = float(input("Enter number 1: "))
y = float(input("Enter number 2: "))

print("{0} + {1} = {2}".format(x, y, x + y))
print("{0} - {1} = {2}".format(x, y, x - y))
print("{0} * {1} = {2}".format(x, y, x * y))
print("{0} / {1} = {2}".format(x, y, x / y))
print("{0} ** {1} = {2}".format(x, y, x ** y))
print("{0} // {1} = {2}".format(x, y, x // y))
print("{0} % {1} = {2}".format(x, y, x % y))
