x = float(input("Enter number 1: "))
y = float(input("Enter number 2: "))

print(str(x) + " + " + str(y) + " = " + str(x + y))
print(str(x) + " - " + str(y) + " = " + str(x - y))
print(str(x) + " * " + str(y) + " = " + str(x * y))
print(str(x) + " / " + str(y) + " = " + str(x / y))
print(str(x) + " ** " + str(y) + " = " + str(x ** y))
print(str(x) + " // " + str(y) + " = " + str(x // y))
print(str(x) + " % " + str(y) + " = " + str(x % y))
